---
# Copyright 2018, Vexxhost, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

journalbeat_service_state: restarted

journalbeat_ilm_policy_name: "journalbeat-{{ beat_version }}"
journalbeat_ilm_policy_template: "journalbeat-{{ beat_version }}"
journalbeat_ilm_policy_filename: "journalbeat-ilm-policy.json"
journalbeat_ilm_policy_file_location: "/etc/journalbeat"

# Manually define Kibana targets.
# Default: hosts from Ansible `kibana` group will be used
journalbeat_kibana_target: "{{ kibana_target | default('') }}"

ilm_policy_name: "{{ journalbeat_ilm_policy_name | default('') }}"
ilm_policy: "{{ (journalbeat_ilm_policy | default(default_ilm_policy)) | default({}) }}"
ilm_policy_template: "{{ journalbeat_ilm_policy_template | default('') }}"
ilm_policy_filename: "{{ (journalbeat_ilm_policy_filename | default(default_ilm_policy_filename)) | default('') }}"
ilm_policy_file_location: "{{ (journalbeat_ilm_policy_file_location | default(default_ilm_policy_file_location)) | default('') }}"

# beat processors. Empty dictionary sets `add_host_metadata: ~`
processors: {}

# Logging level
# Available log levels are error, warning, info, debug
journalbeat_log_level: "{{ elastic_beat_log_level | default('info') }}"

## Journalbeat event queue configuration
# Determines conditions under which the journalbeat event queue is flushed to logstash
# Max # of events the queue can buffer
journalbeat_queue_flush_max_events: 4096

# Min # of events before queue is flushed
journalbeat_queue_flush_min_events: 2048

# Max time before queue is flushed (even if queue_min_events is not reached)
journalbeat_queue_flush_timeout: 1s

# Position to start reading from journal. Valid values: head, tail, cursor
journalbeat_seek: head

# Override flag to force Beats to set up index templates. If this is not
# set, templates are only pushed when the user is either upgrading the
# beat version or deploying for the first time in the presence of kibana nodes
elk_beat_setup: false

# Authentication credentials for monitoring when using ELK security features
# beats_system_username: ""
# beats_system_password: ""
