# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "ubuntu/bionic64"
    #config.vm.box = "ubuntu/xenial64"
    #config.vm.box = "boxcutter/ubuntu1604"
    #config.vm.box = "ubuntu/trusty64"
    #config.vm.box = "centos/7"
    #config.vm.box = "generic/alpine36"

    config.vm.provision :ansible do |ansible|
       ansible.playbook = "site.yml"
       #ansible.verbose = "vvvv"
       #ansible.host_key_checking = false
       #ansible.limit = 'all'
       ansible.become = true
       ansible.extra_vars = { ansible_user: 'vagrant', ansible_python_interpreter: '/usr/bin/python3' }
       ansible.groups = {
          "myrole" => ["osquery" ],
       }
    end

     config.vm.define "vosquery" do |cfg|
        cfg.vm.hostname = "vosquery"
        cfg.vm.provider "virtualbox" do |v|
          v.memory = 512
        end

     end

end

