---
# Copyright 2018, Vexxhost, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

packetbeat_service_state: restarted

packetbeat_ilm_policy_name: "packetbeat-{{ beat_version }}"
packetbeat_ilm_policy_template: "packetbeat-{{ beat_version }}"
packetbeat_ilm_policy_filename: "packetbeat-ilm-policy.json"
packetbeat_ilm_policy_file_location: "/etc/packetbeat"

# Manually define Kibana targets.
# Default: hosts from Ansible `kibana` group will be used
packetbeat_kibana_target: "{{ kibana_target | default('') }}"

ilm_policy_name: "{{ packetbeat_ilm_policy_name | default('') }}"
ilm_policy: "{{ (packetbeat_ilm_policy | default(default_ilm_policy)) | default({}) }}"
ilm_policy_template: "{{ packetbeat_ilm_policy_template | default('') }}"
ilm_policy_filename: "{{ (packetbeat_ilm_policy_filename | default(default_ilm_policy_filename)) | default('') }}"
ilm_policy_file_location: "{{ (packetbeat_ilm_policy_file_location | default(default_ilm_policy_file_location)) | default('') }}"

# beat processors. Empty dictionary sets `add_host_metadata: ~`
processors: {}


# optional list of ports to ignore
packetbeat_ignored_ports: []

# Logging level
# Available log levels are error, warning, info, debug
packetbeat_log_level: "{{ elastic_beat_log_level | default('info') }}"

# Override flag to force Beats to set up index templates. If this is not
# set, templates are only pushed when the user is either upgrading the
# beat version or deploying for the first time in the presence of kibana nodes
elk_beat_setup: false

# Authentication credentials for monitoring when using ELK security features
# beats_system_username: ""
# beats_system_password: ""
