---
- name: load beats dashboards to Kibana
  hosts: kibana
  become: true
  vars_files:
    - vars/variables.yml
  tasks:
    - name: Ensure unzip & curl are installed.
      apt: name={{ item }} state=present update_cache=yes
      with_items:
        - unzip
        - curl
    - name: download sample dashboards
      unarchive:
        src: https://download.elastic.co/beats/dashboards/beats-dashboards-1.1.0.zip
        dest: /root/
        remote_src: yes
    - command: ./load.sh
      args:
       chdir: /root/beats-dashboards-1.1.0
    - name: copy topbeat index template in Elastic search
      copy: src=templates/topbeat.template.json dest=/root mode=0644
    - name: load it in elasticsearch 
      command: "curl -XPUT 'http://localhost:{{ elastic_port }}/_template/topbeat' -d@topbeat.template.json"
      args:
       chdir: /root/

