---
# Copyright 2018, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Install osquery
  hosts: "osquery"
  become: true
  vars_files:
    - vars/variables.yml

  environment: "{{ deployment_environment_variables | default({}) }}"

  gather_facts: "{{ osa_gather_facts | default(True) }}"

  pre_tasks:
    - name: create osquery dir
      file:
        path: /etc/osquery/ssl
        state: directory

    - name: Debug fleet_config
      debug:
        var: hostvars[groups['fleet'][0]]['ansible_host']
        verbosity: 2

    - name: Store ssl cert
      slurp:
        src: "{{ kolide_fleet_ssl_cert }}"
      register: _kolide_fleet_ssl_cert

    - name: Store ssl key
      slurp:
        src: "{{ kolide_fleet_ssl_key }}"
      register: _kolide_fleet_ssl_key

    - name: Register a fact for the cert and key
      set_fact:
        kolide_fleet_ssl_cert_fact: "{{ _kolide_fleet_ssl_cert.content }}"
        kolide_fleet_ssl_key_fact: "{{ _kolide_fleet_ssl_key.content }}"

    - name: Distribute self signed ssl cert
      copy:
        dest: "{{ kolide_fleet_ssl_cert }}"
        content: "{{ hostvars[groups['fleet'][0]]['kolide_fleet_ssl_cert_fact'] | b64decode }}"
        mode: "0640"

    - name: write enroll secret
      copy:
        dest: "{{ osquery_enroll_secret_dir }}"
        content: "{{ hostvars[groups['fleet'][0]]['kolide_fleet_enroll_secret'] }}"
        mode: "0640"

  roles:
    - role: "osquery"
