---
# Copyright 2018, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Gather variables for each operating system
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_facts['distribution'] | lower }}-{{ ansible_facts['distribution_version'] | lower }}.yml"
        - "{{ ansible_facts['distribution'] | lower }}-{{ ansible_facts['distribution_major_version'] | lower }}.yml"
        - "{{ ansible_facts['os_family'] | lower }}-{{ ansible_facts['distribution_major_version'] | lower }}.yml"
        - "{{ ansible_facts['distribution'] | lower }}.yml"
        - "{{ ansible_facts['os_family'] | lower }}-{{ ansible_facts['distribution_version'].split('.')[0] }}.yml"
        - "{{ ansible_facts['os_family'] | lower }}.yml"
      paths:
        - "{{ role_path }}/vars"
  tags:
    - always

- name: Ensure distro packages are installed
  package:
    name: "{{ kibana_distro_packages }}"
    state: "{{ elk_package_state | default('present') }}"
    update_cache: "{{ (ansible_facts['pkg_mgr'] == 'apt') | ternary('yes', omit) }}"
  register: _package_task
  until: _package_task is success
  retries: 3
  delay: 2
  notify:
    - Enable and restart kibana services
  tags:
    - package_install

- name: create kibana user to access web interface
  htpasswd:
    path: "/etc/nginx/htpasswd.users"
    name: "{{ kibana_username }}"
    password: "{{ kibana_password }}"
    owner: root
    mode: 0644
  when:
    - kibana_enable_basic_auth

- name: Drop Nginx default conf file
  template:
    src: "nginx_default.j2"
    dest: "{{ kibana_nginx_vhost_path }}/default"
  notify:
    - Enable and restart kibana services

- name: Create kibana systemd service config dir
  file:
    path: "/etc/systemd/system/kibana.service.d"
    state: "directory"
    group: "root"
    owner: "root"
    mode: "0755"

- name: Apply systemd options
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644"
  with_items:
    - src: "systemd.general-overrides.conf.j2"
      dest: "/etc/systemd/system/kibana.service.d/kibana-overrides.conf"
  notify:
    - Enable and restart kibana services

- name: Drop kibana conf file
  template:
    src: "kibana.yml.j2"
    dest: "/etc/kibana/kibana.yml"
    mode: "0666"
  notify:
    - Enable and restart kibana services

- name: Set authentication password
  shell: "echo '{{ kibana_system_password }}' | /usr/share/kibana/bin/kibana-keystore add elasticsearch.password --stdin --force"
  no_log: True
  changed_when: False
  when:
    - kibana_system_username is defined
    - kibana_system_password is defined

- name: Set permissions on keystore
  file:
    path: "/etc/kibana/kibana.keystore"
    group: "kibana"
    owner: "root"
    mode: "0660"
  when:
    - kibana_system_username is defined
    - kibana_system_password is defined
