---
grafana_service_port: 3000

## When false, HAProxy will be configured to listen only on an Internal VIP
grafana_public_bind: false
grafana_allowlist_networks: "{{ grafana_public_bind | ternary(['0.0.0.0/0'], ['192.168.0.0/16', '172.16.0.0/12', '10.0.0.0/8']) }}"
grafana_haproxy_bind: |-
  {% set binds = [{
          'address': haproxy_bind_internal_lb_vip_address | default(internal_lb_vip_address),
          'interface': haproxy_bind_internal_lb_vip_interface | default('')
  }] %}
  {% if grafana_public_bind %}
  {%  set _ = binds.append({
          'address': haproxy_bind_external_lb_vip_address | default(external_lb_vip_address),
          'interface': haproxy_bind_external_lb_vip_interface | default('')
  }) %}
  {% endif %}
  {{ binds }}

haproxy_grafana_service:
  haproxy_service_name: grafana_all
  haproxy_backend_nodes: "{{ groups['grafana_all'] | default([]) }}"
  haproxy_ssl: "{{ haproxy_ssl }}"
  haproxy_ssl_all_vips: "{{ haproxy_ssl_all_vips }}"
  haproxy_port: "{{ grafana_service_port }}"
  haproxy_balance_type: http
  haproxy_bind: "{{ grafana_haproxy_bind }}"
  haproxy_backend_options:
    - "forwardfor"
    - "httplog"
  haproxy_backend_httpcheck_options:
    - 'send hdr User-Agent "osa-haproxy-healthcheck" meth GET uri /healthcheck'
  haproxy_allowlist_networks: "{{ grafana_allowlist_networks }}"
  haproxy_accept_both_protocols: "{{ grafana_accept_both_protocols | default(openstack_service_accept_both_protocols) }}"
  haproxy_service_enabled: "{{ groups['grafana_all'] is defined and groups['grafana_all'] | length > 0 }}"

grafana_haproxy_services:
  - "{{ haproxy_grafana_service | combine(haproxy_grafana_service_overrides | default({})) }}"
